# Generated by Django 3.0.2 on 2020-02-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200208_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contact_no',
            field=models.CharField(max_length=20, unique=True, verbose_name='Contact Number'),
        ),
    ]
